<?php

namespace Proxies\__CG__\Acme\RestaurantsBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Places extends \Acme\RestaurantsBundle\Entity\Places implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setPlacesId($placesId)
    {
        $this->__load();
        return parent::setPlacesId($placesId);
    }

    public function getPlacesId()
    {
        $this->__load();
        return parent::getPlacesId();
    }

    public function setPlacesName($placesName)
    {
        $this->__load();
        return parent::setPlacesName($placesName);
    }

    public function getPlacesName()
    {
        $this->__load();
        return parent::getPlacesName();
    }

    public function setPlacesAddress($placesAddress)
    {
        $this->__load();
        return parent::setPlacesAddress($placesAddress);
    }

    public function getPlacesAddress()
    {
        $this->__load();
        return parent::getPlacesAddress();
    }

    public function setPlacesRating($placesRating)
    {
        $this->__load();
        return parent::setPlacesRating($placesRating);
    }

    public function getPlacesRating()
    {
        $this->__load();
        return parent::getPlacesRating();
    }

    public function setPlacesLat($placesLat)
    {
        $this->__load();
        return parent::setPlacesLat($placesLat);
    }

    public function getPlacesLat()
    {
        $this->__load();
        return parent::getPlacesLat();
    }

    public function setPlacesLng($placesLng)
    {
        $this->__load();
        return parent::setPlacesLng($placesLng);
    }

    public function getPlacesLng()
    {
        $this->__load();
        return parent::getPlacesLng();
    }

    public function setPlacesOpenNow($placesOpenNow)
    {
        $this->__load();
        return parent::setPlacesOpenNow($placesOpenNow);
    }

    public function getPlacesOpenNow()
    {
        $this->__load();
        return parent::getPlacesOpenNow();
    }

    public function setPlacesReference($placesReference)
    {
        $this->__load();
        return parent::setPlacesReference($placesReference);
    }

    public function getPlacesReference()
    {
        $this->__load();
        return parent::getPlacesReference();
    }

    public function setPlacesTypes($placesTypes)
    {
        $this->__load();
        return parent::setPlacesTypes($placesTypes);
    }

    public function getPlacesTypes()
    {
        $this->__load();
        return parent::getPlacesTypes();
    }

    public function setPlacesIcon($placesIcon)
    {
        $this->__load();
        return parent::setPlacesIcon($placesIcon);
    }

    public function getPlacesIcon()
    {
        $this->__load();
        return parent::getPlacesIcon();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'placesId', 'placesName', 'placesAddress', 'placesRating', 'placesLat', 'placesLng', 'placesOpenNow', 'placesReference', 'placesTypes', 'placesIcon', 'id', 'images');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}